[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  ROLLUP_USE_NODE_JS = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/astro-ssr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

